FROM node:7.4

# create sources directory
RUN mkdir /src

# install some packages globally

RUN npm install per-env -g
RUN npm install pm2 -g
RUN npm install nodemon -g

# set workdir for the next instructions
WORKDIR /src

# copy the package.json from the host to the filesystem of the image
ADD app/package.json /src/package.json

# install the dependencies on the container using the package.json file that was copied
RUN npm install

# define which port the container will listen to
EXPOSE 3000

# set workdir for the next instructions
WORKDIR /src/app

# define commands to be executed when running a container
CMD npm start
